### PR TITLE
bug: fix bottom bar not appearing on some occasions

### PR DESCRIPTION
**Pull request by AnotherMedo**
Not much to this one.. just a small oversight that unfortunately got merged. Easily fixed thankfully 😅

### CODE REVIEW

**Comment by AnotherMedo** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66) **Quality Gate failed**
> Failed conditions  [35.71% Line Coverage on New Code](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66)

I can't really test any new code here since I added 20 something lines 😅

**Review by ramshty — DISMISSED** [review]
Really good changes that improves logic to ensure the bottom bar is displayed correctly upon exiting the login/register flow.

**Comment by Sebbayra** [comment]
> > ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66) **Quality Gate failed**
> > Failed conditions  [35.71% Line Coverage on New Code](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66) (required ≥ 80%)
> > [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=arygm_QuickFix&pullRequest=66)
> 
> I can't really test any new code here since I added 20 something lines 😅

Yeah, the fix is food however sonar is causing us a bit of trouble here, maybe just commit it on main seeing that you can't test these new lines, but i'll see if i can test them now.

**Review by Sebbayra — APPROVED** [review]
Added a helper function test, so now sonar passes. Can merge.

**Pull request merged**
